### ISSUE TITLE
Throw raw input into its own database

### ISSUE THREAD

**Issue by ali** [crew/metrics2-aggregator#5]
Since we delete the windows and linux log files after importing them, it'd be a good idea to put this data into its own database

**Comment by florence** [comment]
We should just delete the log files and backup the DB.There are to may log files with to much redundant data to be worth it.

**Comment by pranav** [comment]
ChrisN wants us to parse the old log files.

## 

Pranav Gandhi
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by florence** [comment]
After those are imported into the 'production' DB we should delete them as well.
